### ISSUE TITLE
Akita

### ISSUE THREAD

**Issue by NetanelBasal** [hamedbaatour/ng-add#1]
`ng add @datorama/akita`

Thanks in advance.

**Comment by hamedbaatour** [comment]
@NetanelBasal do you have Akita logo in SVG format or at least a high res raster image?

**Comment by NetanelBasal** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<svg width="98px" height="86px" viewBox="0 0 98 86" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    
    <title>Group 21</title>
    <desc>Created with Sketch.</desc>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="A-Copy-2" transform="translate(-547.000000, -60.000000)">
            <g id="Group-2" transform="translate(244.000000, 45.000000)">
                <g id="Group-21" transform="translate(303.000000, 15.000000)">
                    <polygon id="Rectangle-62" fill="#FEFEFE" points="15.5002515 14.6096075 78.6822289 14.6096075 78.6822289 68.8896355 15.5002515 68.8896355"></polygon>
                    <g id="Group-Copy">
                        <polygon id="Fill-7" fill="#C7764E" points="70.008731 7.15015169 72.459247 17.8046772 74.9641983 21.8922393 49.2317511 39.7808205 21.7355967 21.8075992 27.7317951 15.6932761 28.2447797 8.77579252 27.6644429 7.15199169"></polygon>
                        <polygon id="Fill-9" fill="#AA6B44" points="4.5616871 35.5102703 14.371132 26.7601458 17.4545748 25.9229454 28.009508 44.7838751 0.0232503772 58.4734821"></polygon>
                        <polygon id="Fill-11" fill="#AA6B44" points="97.5781426 58.4229741 67.8745265 46.9653055 79.1808477 23.879942 93.026789 35.5830423"></polygon>
                        <polygon id="Fill-17" fill="#BCAC9C" points="82.8796601 27.210118 83.7792282 20.7075547 85.6715506 13.2316308 86.6440069 4.58822637 87.2797017 3.38394574 89.2033936 4.49254632 95.7983816 9.82670907 93.026789 35.5830423"></polygon>
                        <path d="M14.7646354,27.202482 C11.7374732,30.4280037 8.02387125,32.8163249 4.56214842,35.5100863 C3.2787645,26.9761619 2.20758641,18.4192375 1.84037807,9.78871305 C4.52247516,8.98923263 6.95822896,9.68199299 9.29526092,11.0049537 C9.89312776,11.4161939 10.3987312,11.9194341 10.8148391,12.5128345 C12.5567722,17.2931569 15.5184274,21.7523992 14.7646354,27.202482" id="Fill-19" fill="#BCAC9C"></path>
                        <path d="M75.2653461,77.2667918 L92.7657101,66.1003495 C86.909675,76.6012646 81.538583,82.7198293 76.6524341,84.4560435 C71.7662851,86.1922578 63.845349,84.7968011 52.8896259,80.2696734 L61.9886426,77.9117122 L62.7452025,77.8132721 L75.2653461,77.2667918 Z" id="Fill-21" fill="#D1D2C3"></path>
                        <path d="M21.9716821,84.4560435 C15.3370777,82.4341458 9.38485687,76.0469108 4.11501979,65.2943384 L22.8829843,77.65632 L35.5525946,77.9277202 L39.0089662,80.7760416 C34.2853813,85.251274 28.6062866,86.4779412 21.9716821,84.4560435 Z" id="Fill-23" fill="#D1D2C3"></path>
                        <polygon id="Fill-25" fill="#9C5D3E" points="89.3240742 4.0781781 73.6752786 12.8963826 79.8924202 18.2736891 74.6357406 21.7247072 65.3993805 11.1084986 70.0096537 7.14913969 88.565669 0.525136271"></polygon>
                        <polygon id="Fill-27" fill="#9C5D3D" points="32.3500773 12.5514404 22.2089079 21.7560792 18.268338 17.8929972 20.4189979 16.2563164 23.9194714 13.1089948 20.1006892 9.06191267 8.5049647 4.97029358 9.07169985 0.0324785324 27.6644429 7.15199169"></polygon>
                        <path d="M62.7391131,78.2000403 L57.7857679,70.4559363 L53.8818265,66.4240342 L52.8598248,57.6338897 L45.0524958,57.4305696 L42.2910522,59.8740909 C43.8956481,62.8144857 44.499266,64.9978002 44.101906,66.4240342 C43.7045459,67.8502683 41.8744399,70.0691562 38.6115877,73.0806977 L34.691039,78.2000403 L25.7675996,61.2982516 L27.395126,55.8104488 L33.0794742,50.7173261 L35.628712,48.0024047 L38.1890213,46.2939639 L48.8468282,40.3954779 L59.4299017,46.2691239 L61.1884421,47.8800447 L63.6085111,50.3106859 L64.7147493,50.8378462 L71.9260568,61.2936516 L62.7391131,78.2000403 Z" id="Fill-41" fill="#FEFEFE"></path>
                        <polygon id="Fill-43" fill="#C37D55" points="75.7762085 22.4827876 81.5987075 25.8250602 63.404609 43.1726783 63.404609 35.4016183 53.6603944 35.4016183 74.6358329 21.7247072"></polygon>
                        <path d="M13.3323499,23.5214653 L20.6683715,19.2525373 L41.850679,34.6288179 C35.9458213,35.0695236 32.9933924,35.3271238 32.9933924,35.4016183 C32.9933924,35.4761127 33.2394282,37.9171807 33.7314996,42.724822 L13.3323499,23.5214653 Z" id="Fill-45" fill="#C37D55"></path>
                        <path d="M59.6241161,8.57247242 L36.0342096,8.57247242 C36.0360549,8.41975234 36.0369775,8.26703226 36.0388228,8.11431218 L59.7846544,8.11431218 L59.6241161,8.57247242 Z" id="Fill-53" fill="#C8764A"></path>
                        <polygon id="Fill-55" fill="#FBFBFD" points="25.7669537 61.2986196 21.4051092 65.6880339 10.6656492 67.1600346 4.28102183 65.6880339 8.85728655 53.9120278 23.9382931 46.544572 29.3357021 49.2052134 34.0872673 51.1611344"></polygon>
                        <polyline id="Fill-57" fill="#9C5C3C" points="34.9376591 43.7646986 27.4279136 46.3125567 18.8063957 28.5682608"></polyline>
                        <path d="M28.5251681,44.7283991 L39.1196823,46.5454 L34.852518,51.653804 C32.706572,51.7733923 30.5848461,51.3423383 28.4873401,50.360642 C26.3898342,49.3789456 24.8733315,48.1071983 23.9378318,46.5454 L27.6302131,44.686079 L28.5251681,44.7283991 Z" id="Fill-59" fill="#C39379"></path>
                        <polygon id="Fill-61" fill="#FBFBFD" points="63.6085111 51.1662864 68.3914459 49.1993254 73.7519495 46.578244 89.3287796 54.9658883 93.0015088 65.6880339 76.0250429 64.2160331 71.9260568 61.2936516"></polygon>
                        <polygon id="Fill-65" fill="#9C5C3C" points="78.62301 28.6510968 69.2688391 46.3211254 63.5931031 42.8146141"></polygon>
                        <polygon id="Fill-69" fill="#B2B6BF" points="41.6769913 65.8486746 44.5741101 75.0893347 34.8218836 78.2691302"></polygon>
                        <polygon id="Fill-71" fill="#B2B5BF" points="62.5441526 78.0829289 52.9893627 74.4901384 55.8498752 65.0088597"></polygon>
                        <path d="M79.2517709,18.0788373 C76.0032401,16.9085341 73.9445361,15.6628534 73.0756588,14.3417954 C72.2067814,13.0207374 72.2862328,11.2571237 73.3140128,9.0509544 L88.4015324,4.0791901 L86.4160689,12.8796922 L79.2517709,18.0788373 Z" id="Fill-73" fill="#AC937C"></path>
                        <path d="M9.20382789,11.61519 L9.20382789,3.58782216 L25.0567396,9.92588727 C25.980681,11.2894656 25.7836602,12.7834067 24.4656772,14.4077106 C23.1476942,16.0320144 21.1327824,17.2640953 18.4209417,18.1039533 L9.20382789,11.61519 Z" id="Fill-75" fill="#AC937C"></path>
                        <polygon id="Fill-77" fill="#A99D8B" points="62.4439625 77.9085842 58.5670954 81.9158899 37.5857311 81.9158899 35.2068837 77.8911042 45.2141305 74.1844222 53.442745 74.1844222"></polygon>
                        <polygon id="Fill-83" fill="#212022" points="27.6027186 44.7283071 34.0159477 42.8450661 39.1196823 46.552024 33.1394454 48.445109"></polygon>
                        <polygon id="Fill-93" fill="#7E828B" points="56.0808325 65.7244659 53.4430218 74.1838702 44.2425154 75.0523507 41.5548825 65.7769059"></polygon>
                        <path d="M4.62894712,65.7473739 C13.2554688,60.0997411 20.4753875,58.4511002 26.2887033,60.8014513 C32.1020191,63.1518025 35.1488334,68.9513321 35.4291462,78.2000403 L23.7939009,79.4001809 L4.62894712,65.7473739 Z" id="Fill-13" fill="#DFEBED"></path>
                        <path d="M73.7095083,79.4258489 L62.0010059,78.2000403 C63.8432466,68.3265429 66.979987,62.5144093 71.411227,60.7636393 C75.842467,59.0128694 82.9495531,60.7776973 92.7324853,66.0581229 L73.7095083,79.4258489 Z" id="Fill-15" fill="#DFEBED"></path>
                        <path d="M56.0801866,65.7243739 L49.1341042,70.0186868 L41.5551593,65.7768139 C41.27708,61.8974572 41.270314,59.4919626 41.5348613,58.5603302 C41.7994087,57.6286978 42.6796015,56.9583241 44.1754399,56.5492092 C49.2304919,56.3707282 52.3406912,56.3768616 53.5060377,56.5676092 C55.2540575,56.8537305 56.0801866,56.2814878 56.4621113,58.5603302 C56.7167278,60.0795585 56.5894196,62.467573 56.0801866,65.7243739 Z" id="Fill-81" fill="#212022"></path>
                        <path d="M88.565669,0.525136271 C90.9711848,-0.230046293 96.3187892,6.84442864 95.8000423,9.82542107 C95.454211,11.8127494 92.3327522,12.7926935 86.4356658,12.7652537 C86.2519907,5.10863044 86.9619918,1.02859131 88.565669,0.525136271 Z" id="Fill-31" fill="#D0C2B1"></path>
                        <path d="M70.0589223,44.673199 L73.7522263,46.57852 C72.1920454,48.5217496 70.6764653,49.7735636 69.2054859,50.333962 C67.7345064,50.8943603 65.5746202,51.042787 62.7258272,50.7792422 L59.5753254,46.57852 L64.1691237,44.673199 L70.0589223,44.673199 Z" id="Fill-67" fill="#C29278"></path>
                        <polygon id="Fill-63" fill="#452922" points="74.3969363 21.6859565 86.3835199 12.8016404 83.6818421 27.8770925"></polygon>
                        <polygon id="Fill-33" fill="#E2B48F" points="89.3287796 54.9667163 97.5780503 58.4222381 92.6957692 66.2328691"></polygon>
                        <polygon id="Fill-85" fill="#212022" points="59.6246557 46.6035719 63.5931031 42.8147981 70.2316807 44.6645181 64.7200912 48.427721"></polygon>
                        <path d="M9.822241,12.1054633 C4.6384694,12.7490454 1.97747937,11.9768874 1.83927091,9.78898905 C1.63195823,6.50714157 7.26074185,-0.490444793 9.05953622,0.031523942 C10.2587325,0.379503099 10.5129674,4.40414954 9.822241,12.1054633 Z" id="Fill-29" fill="#D0C2B1"></path>
                        <polygon id="Fill-51" fill="#442822" points="23.3520291 20.7798818 14.7951392 27.4056372 9.85985816 11.9686761"></polygon>
                        <polygon id="Fill-35" fill="#E1B28E" points="4.62830128 65.7479259 0.023434904 58.4725621 9.04894935 53.9569497"></polygon>
                    </g>
                </g>
            </g>
        </g>
    </g>
</svg>

**Comment by NetanelBasal** [comment]
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg width="98px" height="86px" viewBox="0 0 98 86" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 53 (72520) - https://sketchapp.com -->
    <title>Group 21</title>
    <desc>Created with Sketch.</desc>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="A-Copy-2" transform="translate(-547.000000, -60.000000)">
            <g id="Group-2" transform="translate(244.000000, 45.000000)">
                <g id="Group-21" transform="translate(303.000000, 15.000000)">
                    <polygon id="Rectangle-62" fill="#FEFEFE" points="15.5002515 14.6096075 78.6822289 14.6096075 78.6822289 68.8896355 15.5002515 68.8896355"></polygon>
                    <g id="Group-Copy">
                        <polygon id="Fill-7" fill="#C7764E" points="70.008731 7.15015169 72.459247 17.8046772 74.9641983 21.8922393 49.2317511 39.7808205 21.7355967 21.8075992 27.7317951 15.6932761 28.2447797 8.77579252 27.6644429 7.15199169"></polygon>
                        <polygon id="Fill-9" fill="#AA6B44" points="4.5616871 35.5102703 14.371132 26.7601458 17.4545748 25.9229454 28.009508 44.7838751 0.0232503772 58.4734821"></polygon>
                        <polygon id="Fill-11" fill="#AA6B44" points="97.5781426 58.4229741 67.8745265 46.9653055 79.1808477 23.879942 93.026789 35.5830423"></polygon>
                        <polygon id="Fill-17" fill="#BCAC9C" points="82.8796601 27.210118 83.7792282 20.7075547 85.6715506 13.2316308 86.6440069 4.58822637 87.2797017 3.38394574 89.2033936 4.49254632 95.7983816 9.82670907 93.026789 35.5830423"></polygon>
                        <path d="M14.7646354,27.202482 C11.7374732,30.4280037 8.02387125,32.8163249 4.56214842,35.5100863 C3.2787645,26.9761619 2.20758641,18.4192375 1.84037807,9.78871305 C4.52247516,8.98923263 6.95822896,9.68199299 9.29526092,11.0049537 C9.89312776,11.4161939 10.3987312,11.9194341 10.8148391,12.5128345 C12.5567722,17.2931569 15.5184274,21.7523992 14.7646354,27.202482" id="Fill-19" fill="#BCAC9C"></path>
                        <path d="M75.2653461,77.2667918 L92.7657101,66.1003495 C86.909675,76.6012646 81.538583,82.7198293 76.6524341,84.4560435 C71.7662851,86.1922578 63.845349,84.7968011 52.8896259,80.2696734 L61.9886426,77.9117122 L62.7452025,77.8132721 L75.2653461,77.2667918 Z" id="Fill-21" fill="#D1D2C3"></path>
                        <path d="M21.9716821,84.4560435 C15.3370777,82.4341458 9.38485687,76.0469108 4.11501979,65.2943384 L22.8829843,77.65632 L35.5525946,77.9277202 L39.0089662,80.7760416 C34.2853813,85.251274 28.6062866,86.4779412 21.9716821,84.4560435 Z" id="Fill-23" fill="#D1D2C3"></path>
                        <polygon id="Fill-25" fill="#9C5D3E" points="89.3240742 4.0781781 73.6752786 12.8963826 79.8924202 18.2736891 74.6357406 21.7247072 65.3993805 11.1084986 70.0096537 7.14913969 88.565669 0.525136271"></polygon>
                        <polygon id="Fill-27" fill="#9C5D3D" points="32.3500773 12.5514404 22.2089079 21.7560792 18.268338 17.8929972 20.4189979 16.2563164 23.9194714 13.1089948 20.1006892 9.06191267 8.5049647 4.97029358 9.07169985 0.0324785324 27.6644429 7.15199169"></polygon>
                        <path d="M62.7391131,78.2000403 L57.7857679,70.4559363 L53.8818265,66.4240342 L52.8598248,57.6338897 L45.0524958,57.4305696 L42.2910522,59.8740909 C43.8956481,62.8144857 44.499266,64.9978002 44.101906,66.4240342 C43.7045459,67.8502683 41.8744399,70.0691562 38.6115877,73.0806977 L34.691039,78.2000403 L25.7675996,61.2982516 L27.395126,55.8104488 L33.0794742,50.7173261 L35.628712,48.0024047 L38.1890213,46.2939639 L48.8468282,40.3954779 L59.4299017,46.2691239 L61.1884421,47.8800447 L63.6085111,50.3106859 L64.7147493,50.8378462 L71.9260568,61.2936516 L62.7391131,78.2000403 Z" id="Fill-41" fill="#FEFEFE"></path>
                        <polygon id="Fill-43" fill="#C37D55" points="75.7762085 22.4827876 81.5987075 25.8250602 63.404609 43.1726783 63.404609 35.4016183 53.6603944 35.4016183 74.6358329 21.7247072"></polygon>
                        <path d="M13.3323499,23.5214653 L20.6683715,19.2525373 L41.850679,34.6288179 C35.9458213,35.0695236 32.9933924,35.3271238 32.9933924,35.4016183 C32.9933924,35.4761127 33.2394282,37.9171807 33.7314996,42.724822 L13.3323499,23.5214653 Z" id="Fill-45" fill="#C37D55"></path>
                        <path d="M59.6241161,8.57247242 L36.0342096,8.57247242 C36.0360549,8.41975234 36.0369775,8.26703226 36.0388228,8.11431218 L59.7846544,8.11431218 L59.6241161,8.57247242 Z" id="Fill-53" fill="#C8764A"></path>
                        <polygon id="Fill-55" fill="#FBFBFD" points="25.7669537 61.2986196 21.4051092 65.6880339 10.6656492 67.1600346 4.28102183 65.6880339 8.85728655 53.9120278 23.9382931 46.544572 29.3357021 49.2052134 34.0872673 51.1611344"></polygon>
                        <polyline id="Fill-57" fill="#9C5C3C" points="34.9376591 43.7646986 27.4279136 46.3125567 18.8063957 28.5682608"></polyline>
                        <path d="M28.5251681,44.7283991 L39.1196823,46.5454 L34.852518,51.653804 C32.706572,51.7733923 30.5848461,51.3423383 28.4873401,50.360642 C26.3898342,49.3789456 24.8733315,48.1071983 23.9378318,46.5454 L27.6302131,44.686079 L28.5251681,44.7283991 Z" id="Fill-59" fill="#C39379"></path>
                        <polygon id="Fill-61" fill="#FBFBFD" points="63.6085111 51.1662864 68.3914459 49.1993254 73.7519495 46.578244 89.3287796 54.9658883 93.0015088 65.6880339 76.0250429 64.2160331 71.9260568 61.2936516"></polygon>
                        <polygon id="Fill-65" fill="#9C5C3C" points="78.62301 28.6510968 69.2688391 46.3211254 63.5931031 42.8146141"></polygon>
                        <polygon id="Fill-69" fill="#B2B6BF" points="41.6769913 65.8486746 44.5741101 75.0893347 34.8218836 78.2691302"></polygon>
                        <polygon id="Fill-71" fill="#B2B5BF" points="62.5441526 78.0829289 52.9893627 74.4901384 55.8498752 65.0088597"></polygon>
                        <path d="M79.2517709,18.0788373 C76.0032401,16.9085341 73.9445361,15.6628534 73.0756588,14.3417954 C72.2067814,13.0207374 72.2862328,11.2571237 73.3140128,9.0509544 L88.4015324,4.0791901 L86.4160689,12.8796922 L79.2517709,18.0788373 Z" id="Fill-73" fill="#AC937C"></path>
                        <path d="M9.20382789,11.61519 L9.20382789,3.58782216 L25.0567396,9.92588727 C25.980681,11.2894656 25.7836602,12.7834067 24.4656772,14.4077106 C23.1476942,16.0320144 21.1327824,17.2640953 18.4209417,18.1039533 L9.20382789,11.61519 Z" id="Fill-75" fill="#AC937C"></path>
                        <polygon id="Fill-77" fill="#A99D8B" points="62.4439625 77.9085842 58.5670954 81.9158899 37.5857311 81.9158899 35.2068837 77.8911042 45.2141305 74.1844222 53.442745 74.1844222"></polygon>
                        <polygon id="Fill-83" fill="#212022" points="27.6027186 44.7283071 34.0159477 42.8450661 39.1196823 46.552024 33.1394454 48.445109"></polygon>
                        <polygon id="Fill-93" fill="#7E828B" points="56.0808325 65.7244659 53.4430218 74.1838702 44.2425154 75.0523507 41.5548825 65.7769059"></polygon>
                        <path d="M4.62894712,65.7473739 C13.2554688,60.0997411 20.4753875,58.4511002 26.2887033,60.8014513 C32.1020191,63.1518025 35.1488334,68.9513321 35.4291462,78.2000403 L23.7939009,79.4001809 L4.62894712,65.7473739 Z" id="Fill-13" fill="#DFEBED"></path>
                        <path d="M73.7095083,79.4258489 L62.0010059,78.2000403 C63.8432466,68.3265429 66.979987,62.5144093 71.411227,60.7636393 C75.842467,59.0128694 82.9495531,60.7776973 92.7324853,66.0581229 L73.7095083,79.4258489 Z" id="Fill-15" fill="#DFEBED"></path>
                        <path d="M56.0801866,65.7243739 L49.1341042,70.0186868 L41.5551593,65.7768139 C41.27708,61.8974572 41.270314,59.4919626 41.5348613,58.5603302 C41.7994087,57.6286978 42.6796015,56.9583241 44.1754399,56.5492092 C49.2304919,56.3707282 52.3406912,56.3768616 53.5060377,56.5676092 C55.2540575,56.8537305 56.0801866,56.2814878 56.4621113,58.5603302 C56.7167278,60.0795585 56.5894196,62.467573 56.0801866,65.7243739 Z" id="Fill-81" fill="#212022"></path>
                        <path d="M88.565669,0.525136271 C90.9711848,-0.230046293 96.3187892,6.84442864 95.8000423,9.82542107 C95.454211,11.8127494 92.3327522,12.7926935 86.4356658,12.7652537 C86.2519907,5.10863044 86.9619918,1.02859131 88.565669,0.525136271 Z" id="Fill-31" fill="#D0C2B1"></path>
                        <path d="M70.0589223,44.673199 L73.7522263,46.57852 C72.1920454,48.5217496 70.6764653,49.7735636 69.2054859,50.333962 C67.7345064,50.8943603 65.5746202,51.042787 62.7258272,50.7792422 L59.5753254,46.57852 L64.1691237,44.673199 L70.0589223,44.673199 Z" id="Fill-67" fill="#C29278"></path>
                        <polygon id="Fill-63" fill="#452922" points="74.3969363 21.6859565 86.3835199 12.8016404 83.6818421 27.8770925"></polygon>
                        <polygon id="Fill-33" fill="#E2B48F" points="89.3287796 54.9667163 97.5780503 58.4222381 92.6957692 66.2328691"></polygon>
                        <polygon id="Fill-85" fill="#212022" points="59.6246557 46.6035719 63.5931031 42.8147981 70.2316807 44.6645181 64.7200912 48.427721"></polygon>
                        <path d="M9.822241,12.1054633 C4.6384694,12.7490454 1.97747937,11.9768874 1.83927091,9.78898905 C1.63195823,6.50714157 7.26074185,-0.490444793 9.05953622,0.031523942 C10.2587325,0.379503099 10.5129674,4.40414954 9.822241,12.1054633 Z" id="Fill-29" fill="#D0C2B1"></path>
                        <polygon id="Fill-51" fill="#442822" points="23.3520291 20.7798818 14.7951392 27.4056372 9.85985816 11.9686761"></polygon>
                        <polygon id="Fill-35" fill="#E1B28E" points="4.62830128 65.7479259 0.023434904 58.4725621 9.04894935 53.9569497"></polygon>
                    </g>
                </g>
            </g>
        </g>
    </g>
</svg>
```

**Comment by hamedbaatour** [comment]
- **@NetanelBasal Your library was added and published**
please give ngadd repo a star ⭐️ 


![image](https://user-images.githubusercontent.com/5658460/57012194-f9a18e80-6c0d-11e9-9b1e-c187ce5b4fa5.png)

**Comment by NetanelBasal** [comment]
Thanks
