### ISSUE TITLE
Formly

### ISSUE THREAD

**Issue by aitboudad** [hamedbaatour/ng-add#2]
Repo: https://github.com/ngx-formly/ngx-formly

```batch
ng add @ngx-formly/schematics --ui-theme=material
```

**Comment by hamedbaatour** [comment]
do you have ngx-formly logo in an SVG format?

**Comment by aitboudad** [comment]
https://github.com/ngx-formly/ngx-formly/blob/master/logo/logo.svg

**Comment by hamedbaatour** [comment]
- @aitboudad **Your library was added and the changes are now live:**

![image](https://user-images.githubusercontent.com/5658460/57014414-a97bf980-6c18-11e9-8596-292593e6e609.png)

**Comment by aitboudad** [comment]
awesome :+1:, thanks!
