### ISSUE TITLE
Add OktaDev Schematics

### ISSUE THREAD

**Issue by mraible** [hamedbaatour/ng-add#3]
Repo: [oktadeveloper/schematics](https://github.com/oktadeveloper/schematics)

```
ng add @oktadev/schematics
```

Logo:

![oktadev-logo](https://user-images.githubusercontent.com/17892/57031797-e4c0fd00-6c05-11e9-984e-4f8634bda2c2.png)

**Comment by hamedbaatour** [comment]
@mraible **your library was added to ngadd.com** 
![image](https://user-images.githubusercontent.com/5658460/57077156-fd0f4580-6cf3-11e9-96cc-3f360664e849.png)
