### ISSUE TITLE
Add NGXS 

### ISSUE THREAD

**Issue by Waterstraal** [hamedbaatour/ng-add#4]
To add [@ngxs/store](https://github.com/ngxs/store) you can run `ng add @ngxs/schematics`. 
See https://github.com/ngxs/schematics for more information.

The logo and other information about NGXS can be found here: [ngxs.io](https://ngxs.io)

When [this proposal](https://github.com/ngxs/store/issues/769) is accepted and implemented it will hopefully become `ng add @ngxs/store` in the future because the current implementation feels a bit awkward imho.

**Comment by hamedbaatour** [comment]
@Waterstraal **your suggestion has been added to ngadd.com**
![image](https://user-images.githubusercontent.com/5658460/57077074-c89b8980-6cf3-11e9-8ef4-b15cef814a33.png)
