### ISSUE TITLE
Angular Builders are coming!

### ISSUE THREAD

**Issue by JohannesHoppe** [hamedbaatour/ng-add#5]
See https://twitter.com/mgechev/status/1156998284541489153

With the final version of Angular CLI 8.3.0 we will have:
```
ng add [provider]
ng deploy
```

Some builders (with `ng add` support, of course)
* `@angular/fire`
* `@zeit/ng-deploy`
* `@azure/ng-deploy`
* `@netlify-builder/deploy`
* `angular-cli-ghpages` (this one is mine)

**Comment by hamedbaatour** [comment]
@JohannesHoppe thanks for opening this issue. I will definitely add all of the commands as soon as the Angular CLI 8.3.0 gets officially released.

**Comment by hamedbaatour** [comment]
your suggestion has been added to ngadd.com
please don't forget to star ngadd repo ⭐️

![image](https://user-images.githubusercontent.com/5658460/65985749-1840d580-e48b-11e9-8517-f0fba52fe2cd.png)
