### ISSUE TITLE
[Request]: ng add ngx-scrolltop

### ISSUE THREAD

**Issue by bartholomej** [hamedbaatour/ng-add#7]
### Angular ScrollTop Button (ngx-scrolltop)

Thanks for your great idea @hamedbaatour. Here is my contribution:

**Link to library repository:**
https://github.com/bartholomej/ngx-scrolltop/

**Library ngadd command:**
`ng add ngx-scrolltop` ([docs](https://github.com/bartholomej/ngx-scrolltop/#automatically-recommended-))

**Library logo in SVG format**
https://github.com/bartholomej/ngx-scrolltop/blob/master/_assets/ngx-scrolltop_logo.svg

<img src="https://raw.github.com/bartholomej/ngx-scrolltop/master/_assets/ngx-scrolltop_logo.svg?sanitize=true" width="200">

**Comment by hamedbaatour** [comment]
your suggestion has been added to ngadd.com
please don't forget to star ngadd repo ⭐️
![image](https://user-images.githubusercontent.com/5658460/65989435-61485800-e492-11e9-9dad-29f19d0fa27b.png)

**Comment by bartholomej** [comment]
Awesome! Thx for your great project.
